AllCops:
  Exclude:
    - Rakefile
    - bin/*
    - vendor/**/*
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - spec/useragent_api/**/*

Metrics/LineLength:
  Max: 128
  Exclude:
    - spec/useragent_api/**/*

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
